"""GenerateReport — Strands tool implementation."""

from __future__ import annotations

import logging
import os
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

import boto3
from boto3.dynamodb.conditions import Key
from strands import tool

from agent.config import BUCKET_REPORTS
from agent.db import (
    TABLE_ESG,
    TABLE_MARKET,
    TABLE_METRICS,
    TABLE_OPERATORS,
    get_item,
    query_items,
    scan_table,
)

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

PRESIGNED_EXPIRY: int = 3600  # 1 hour


def _generate_markdown_report(
    operator: Dict[str, Any],
    metrics: List[Dict[str, Any]],
    esg: Optional[Dict[str, Any]],
    markets: List[Dict[str, Any]],
) -> str:
    """Compile a Markdown investment research report."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    name = operator.get("name", "Unknown")
    ticker = operator.get("ticker", "N/A")
    rating = operator.get("moodys_rating", "NR")

    lines: List[str] = [
        f"# Data Center Investment Report: {name}",
        f"",
        f"**Generated:** {now}",
        f"**Ticker:** {ticker}  |  **Moody's Rating:** {rating}  |  **Sector:** {operator.get('sector', '')}",
        f"",
        f"---",
        f"",
        f"## 1. Credit Summary",
        f"",
        f"| Attribute | Value |",
        f"|---|---|",
        f"| Issuer Rating | {rating} |",
        f"| Headquarters | {operator.get('hq', 'N/A')} |",
        f"| Market Cap (USD M) | {operator.get('market_cap', 'N/A')} |",
        f"",
    ]

    # Financial metrics section
    if metrics:
        lines.append("## 2. Financial Metrics")
        lines.append("")
        lines.append("| Period | Revenue ($M) | EBITDA ($M) | FFO ($M) | Debt/EBITDA | Int. Coverage | Occupancy | CapEx ($M) | Liquidity ($M) |")
        lines.append("|---|---|---|---|---|---|---|---|---|")
        for m in metrics:
            lines.append(
                f"| {m.get('period', '')} | {m.get('revenue', '')} | {m.get('ebitda', '')} | "
                f"{m.get('ffo', '')} | {m.get('debt_to_ebitda', '')}x | "
                f"{m.get('interest_coverage', '')}x | {float(m.get('occupancy_rate', 0)) * 100:.0f}% | "
                f"{m.get('capex', '')} | {m.get('liquidity', '')} |"
            )
        lines.append("")

    # ESG section
    if esg:
        lines.append("## 3. ESG Profile")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|---|---|")
        lines.append(f"| PUE | {esg.get('pue', 'N/A')} |")
        lines.append(f"| Carbon Intensity (kg CO\u2082e/MWh) | {esg.get('carbon_intensity', 'N/A')} |")
        pct = esg.get("renewable_pct")
        lines.append(f"| Renewable Energy | {float(pct) * 100:.0f}% |" if pct else "| Renewable Energy | N/A |")
        lines.append(f"| Water Usage (L/kWh) | {esg.get('water_usage', 'N/A')} |")
        lines.append(f"| Climate Risk Score | {esg.get('climate_risk_score', 'N/A')} / 100 |")
        lines.append(f"| Green Bonds Outstanding ($M) | {esg.get('green_bond_outstanding', 'N/A')} |")
        lines.append("")

    # Market overview
    if markets:
        lines.append("## 4. Market Overview")
        lines.append("")
        lines.append("| Market | Capacity (MW) | Vacancy | Pricing ($/kW) | Pipeline (MW) | YoY Growth |")
        lines.append("|---|---|---|---|---|---|")
        for mk in markets:
            vr = mk.get("vacancy_rate", 0)
            yoy = mk.get("yoy_growth", 0)
            lines.append(
                f"| {mk.get('market_name', '')} | {mk.get('total_capacity_mw', '')} | "
                f"{float(vr) * 100:.1f}% | ${mk.get('avg_price_per_kw', '')} | "
                f"{mk.get('construction_pipeline_mw', '')} | {float(yoy) * 100:.1f}% |"
            )
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*This report is generated by the Data Center Investments Agent for informational purposes only.*")

    return "\n".join(lines)


@tool
def generate_report(operator_id: str) -> dict:
    """Generate a comprehensive investment research report for a data center operator.

    Args:
        operator_id: Operator ID (e.g., "op-001")

    Returns:
        Report metadata including report ID, S3 location, download URL, and sections generated.
    """
    if not operator_id:
        return {"error": "operator_id parameter is required"}

    # Fetch operator
    operator = get_item(TABLE_OPERATORS, {"id": operator_id})
    if not operator:
        return {"error": f"Operator '{operator_id}' not found"}

    # Fetch financial metrics
    try:
        metrics = query_items(
            TABLE_METRICS,
            Key("operator_id").eq(operator_id),
            scan_index_forward=False,
        )
    except Exception:
        logger.warning("Failed to fetch metrics for report", exc_info=True)
        metrics = []

    # Fetch ESG profile
    try:
        esg = get_item(TABLE_ESG, {"operator_id": operator_id})
    except Exception:
        logger.warning("Failed to fetch ESG for report", exc_info=True)
        esg = None

    # Fetch market data (all markets for context)
    try:
        markets = scan_table(TABLE_MARKET)
    except Exception:
        logger.warning("Failed to fetch market data for report", exc_info=True)
        markets = []

    # Generate report
    report_md = _generate_markdown_report(operator, metrics, esg, markets)

    # Upload to S3
    report_id = f"report-{uuid.uuid4().hex[:12]}"
    s3_key = f"reports/{operator_id}/{report_id}.md"

    presigned_url: Optional[str] = None
    try:
        s3_client = boto3.client("s3")
        s3_client.put_object(
            Bucket=BUCKET_REPORTS,
            Key=s3_key,
            Body=report_md.encode("utf-8"),
            ContentType="text/markdown",
            Metadata={
                "operator_id": operator_id,
                "report_id": report_id,
                "generated_at": datetime.utcnow().isoformat(),
            },
        )

        # Generate presigned URL
        presigned_url = s3_client.generate_presigned_url(
            "get_object",
            Params={"Bucket": BUCKET_REPORTS, "Key": s3_key},
            ExpiresIn=PRESIGNED_EXPIRY,
        )
    except Exception:
        logger.exception("Failed to upload report to S3")

    body: Dict[str, Any] = {
        "report_id": report_id,
        "operator_id": operator_id,
        "operator_name": operator.get("name", ""),
        "format": "markdown",
        "s3_key": s3_key,
        "download_url": presigned_url,
        "expires_in_seconds": PRESIGNED_EXPIRY if presigned_url else None,
        "sections": ["credit_summary", "financial_metrics", "esg_profile", "market_overview"],
    }

    if not presigned_url:
        body["report_content"] = report_md
        body["note"] = "S3 upload failed; report content returned inline."

    return body
